---
abstract: 'Digested hierarchical storage of files'
author:
  - 'Peter Corlett <abuse@cabal.org.uk>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  File::stat: 0
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-DigestStore
requires:
  Algorithm::Nhash: 0
  Carp: 0
  Digest: 0
  IO::File: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Sys::Hostname: 0
  perl: 5.006
version: 1.006
