---
name: File-DigestStore
version: 1.005
author:
  - 'Peter Corlett <abuse@cabal.org.uk>'
abstract: Digested hierarchical storage of files
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Algorithm::Nhash: 0
  Digest::SHA: 0
  Readonly: 0
  Test::Class: 0
  Test::Exception: 0
  Test::More: 0
requires:
  Moose: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  namespace::clean: 0
recommends:
  Pod::Coverage: 0.18
  Test::CheckManifest: 0.9
  Test::Pod: 1.22
  Test::Pod::Coverage: 1.08
configure_requires:
  Module::Build: 0.340201
provides:
  File::DigestStore:
    file: lib/File/DigestStore.pm
    version: 1.005
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
